language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install gfortran gcc
  - sudo pip install --upgrade conda
install:
  # install deps
  - sudo conda init
  - sudo conda update conda --yes
  - deps='pip numpy pandas requests nose numpydoc sphinx pep8 numexpr cython'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  - pip install unittest2
  - conda update pandas
  # install our own package into the environment
  - "pip install ."
script:
  # Download spark 1.0.0
  - "wget http://d3kbcqa49mib13.cloudfront.net/spark-1.0.0-bin-hadoop2.tgz"
  - "tar -xvf spark-1.0.0-bin-hadoop2.tgz"
  # Run the tests
  - "export SPARK_HOME=./spark-1.0.0-bin-hadoop2/"
  - "./run-tests"
  - "pep8 sparklingpandas/"