language: python
python:
  - "2.7"
before_install:
  - wget http://d3kbcqa49mib13.cloudfront.net/spark-1.4.1-bin-hadoop2.4.tgz &> /dev/null &
  - export WGET_PID=$!
  - sudo pip install --upgrade conda py4j
  - sudo conda init
  - deps='pip numpy pandas requests nose numpydoc sphinx pep8 pylint scipy openpyxl'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - pip install unittest2
  - time pip install .
script:
  - ./test_script