language: python
python:
  - "2.6"
  - "2.7"
before_install:
 - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then ./setup_for_travis fi
# command to install dependencies
install:
  - "pip install ."
# command to run tests
script:
  # Download spark 1.0.0
  - "wget http://d3kbcqa49mib13.cloudfront.net/spark-1.0.0-bin-hadoop2.tgz"
  - "tar -xvf spark-1.0.0-bin-hadoop2.tgz"
  # Run the tests
  - "SPARK_HOME=./spark-1.0.0-bin-hadoop2/ ./run-tests"