language: python
python:
  - "2.7"
before_install:
  - sudo pip install --upgrade conda py4j
install:
  # install deps
  - sudo conda init
  - deps='pip numpy pandas requests nose numpydoc sphinx pep8 pylint scipy openpyxl'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  - pip install unittest2
  # install our own package into the environment
  - "pip install ."
script:
  - ./test_script