site_name: SparklingPandas
pages:
- Home: index.md
theme: readthedocs
site_url: http://sparklingpandas.com
repo_url: https://github.com/sparklingpandas/sparklingpandas
google_analytics: ['UA-65642288-1', 'sparklingpandas.com']
